version: '3.8'
services:
  katj:
    image: mysql
    environment:
      MYSQL_DATABASE: katj
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: katj4
    ports:
      - "3306:3306"
  cicd-test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - katj
#    restart: always